services:
  app:
    container_name: elimika
    image: elimika:development
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped