name: "deploy"

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create .env.local file
        run: scripts/create-env.sh
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_KEYCLOAK_REALM: ${{ secrets.NEXT_PUBLIC_KEYCLOAK_REALM }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          KEYCLOAK_ISSUER: ${{ secrets.KEYCLOAK_ISSUER }}
          KEYCLOAK_CLIENT_ID: ${{ secrets.KEYCLOAK_CLIENT_ID }}
          KEYCLOAK_CLIENT_SECRET: ${{ secrets.KEYCLOAK_CLIENT_SECRET }}

      - name: Login to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: scripts/build-and-push.sh
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

  setup_server:
    name: Setup Server
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup SSH Connection & Configure Server
        run: scripts/setup-server.sh
        env:
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SERVER_SSH_USER: ${{ secrets.SERVER_SSH_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}

  deploy:
    name: Deploy to Self-Hosted Server
    runs-on: ubuntu-latest
    needs: setup_server

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: scripts/deploy.sh
        env:
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SERVER_SSH_USER: ${{ secrets.SERVER_SSH_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
          GITHUB_ACTOR: ${{ github.actor }}
