name: "deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create .env.local file for Build
        run: |
          cat <<EOF > .env.local
          NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_KEYCLOAK_REALM=${{ secrets.NEXT_PUBLIC_KEYCLOAK_REALM }}
          NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
          KEYCLOAK_ISSUER=${{ secrets.KEYCLOAK_ISSUER }}
          KEYCLOAK_CLIENT_ID=${{ secrets.KEYCLOAK_CLIENT_ID }}
          KEYCLOAK_CLIENT_SECRET=${{ secrets.KEYCLOAK_CLIENT_SECRET }}
          EOF

      - name: Login to GitHub Container Registry (ghcr.io)
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image to ghcr.io
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/elimika-ui
          docker build -t $IMAGE_NAME:latest -f docker/Dockerfile .
          docker push $IMAGE_NAME:latest

      - name: Deploy to Server
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > private_key
          chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no ${{ secrets.SERVER_SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            export IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/elimika-ui

            # Ensure deployment directory exists
            mkdir -p /home/${{ secrets.SERVER_SSH_USER }}/products/elimika-ui/docker
            cd /home/${{ secrets.SERVER_SSH_USER }}/products/elimika-ui
          
            # Create docker-compose file
            cat << 'EOC' > docker/compose.yaml
            version: "3.8"

            services:
              nextjs-app:
                image: ghcr.io/${{ github.repository_owner }}/elimika-ui:latest
                ports:
                  - "3000:3000"
                env_file:
                  - ../.env.local
                restart: always
            EOC
          
            # Create .env.local file on server for runtime
            cat << 'EOV' > .env.local
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_KEYCLOAK_REALM=${{ secrets.NEXT_PUBLIC_KEYCLOAK_REALM }}
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            KEYCLOAK_ISSUER=${{ secrets.KEYCLOAK_ISSUER }}
            KEYCLOAK_CLIENT_ID=${{ secrets.KEYCLOAK_CLIENT_ID }}
            KEYCLOAK_CLIENT_SECRET=${{ secrets.KEYCLOAK_CLIENT_SECRET }}
            EOV

            # Secure the .env.local file
            chmod 600 .env.local

            # Log in to GHCR
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Deploy with Docker Compose
            cd /home/${{ secrets.SERVER_SSH_USER }}/products/elimika-ui/docker
            docker compose -f compose.yaml pull
            docker compose -f compose.yaml up -d --no-deps --build
            docker system prune -af
          EOF
