name: "deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Login to Github Container Registry (ghcr.io)
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image to ghcr.io
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/elimika-ui
          docker build -t $IMAGE_NAME:latest -f docker/Dockerfile
          docker push $IMAGE_NAME:latest

      - name: Deploy
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > private_key
          chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no ${{ secrets.SERVER_SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            export IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/elimika-ui
            export GITHUB_USERNAME=${{ github.repository_owner }}

            mkdir -p /home/${{ secrets.SERVER_SSH_USER }}/products/elimika-ui/docker
            cd /home/${{ secrets.SERVER_SSH_USER }}/products/elimika-ui
          
            cat << 'EOC' > docker/compose.yaml
            version: "3.8"

            services:
              nextjs-app:
                image: ghcr.io/${{ github.repository_owner }}/elimika-ui:latest
                ports:
                  - "3000:3000"
                env_file:
                  - .env.local
                restart: always
            EOC
          
            cat << 'EOV' > .env.local
            NODE_ENV=production
            PORT=3000
            KEYCLOAK_ISSUER=${{ secrets.KEYCLOAK_ISSUER }}
            KEYCLOAK_CLIENT_ID=${{ secrets.KEYCLOAK_CLIENT_ID }}
            KEYCLOAK_CLIENT_SECRET=${{ secrets.KEYCLOAK_CLIENT_SECRET }}
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_KEYCLOAK_REALM=${{ secrets.NEXT_PUBLIC_KEYCLOAK_REALM }}
          
            EOV

            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            cd /home/${{ secrets.SERVER_SSH_USER }}/products/elimika-ui/docker
            docker compose -f compose.yaml pull
            docker compose -f compose.yaml up -d --no-deps --build
            docker system prune -af
          EOF
